<a href="https://colab.research.google.com/github/aya270/matrixcolab/blob/main/First_Colab_File.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix

In [ ]:
import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6]])



In [ ]:
mean_value=np.mean(matrix)
mean_value

3.5

In [ ]:
mode_value=np.argmax(matrix)+1
mode_value

6

In [ ]:
median_value=np.median(matrix)
median_value

3.5

In [ ]:
matrix2=np.array([[1,2,3],
                 [0,5,8]])

In [ ]:
matrix+matrix2

array([[ 2,  4,  6],
       [ 4, 10, 14]])

In [ ]:
matrix-matrix2

array([[ 0,  0,  0],
       [ 4,  0, -2]])

In [ ]:
matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
2*matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

#List

In [ ]:
lista=[5,8,11,79,55,55]

In [ ]:
max(lista)

79

In [ ]:
min(lista)

5

In [ ]:
sum(lista)

213

In [ ]:
lista[0]

5

In [ ]:
lista.sort()

In [ ]:
lista.append(17)
lista

[5, 8, 11, 55, 55, 79, 17]

In [ ]:
lista.count(55)

2

#Git

In [1]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!git add /content/drive/MyDrive/matrix/First_Colab_File.ipynb

In [4]:
! git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   drive/MyDrive/matrix/First_Colab_File.ipynb

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   drive/MyDrive/matrix/First_Colab_File.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	drive/MyDrive/20231010_New Body Line (3).gsheet
	drive/MyDrive/240950979_4085107668253337_6434636654005548995_n (1).jpg
	drive/MyDrive/240950979_4085107668253337_6434636654005548995_n.jpg
	drive/MyDrive/241043987_555605645754037_4117809719235279948_n (1).jpg
	drive/MyDrive/241043987_555605645754037_4117809719235279948_n (2).jpg
	drive/MyDrive/241043987_555605645754037_4117809719235279948_n.jpg
	drive/MyDrive/241474865_4202502266515126_1043182382451018102_n (1).jpg
	drive/MyDrive/241474865_4202502266515126_1043182382

In [5]:
!git commit -m "Initial commit :)"

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@8ad3138d1235.(none)')


In [9]:
#authentication
!git config --global user.email "ayadhaoui2020@gmail.com"
!git config --global user.name "aya"

In [ ]:
!git commit -m "second commit :) "

In [11]:
import numpy
numpy .__version__

'1.26.4'

In [ ]:
!git commit -m "commit after numpy"